config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: :destroy
  resources :posts, except: :index do
    resource :comments, only: :new
    member do
      post 'upvote'
      post 'downvote'
    end
  end
  resources :comments, only: [:create, :show] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :integer          not null, primary key
#  content           :text             not null
#  user_id           :integer          not null
#  post_id           :integer          not null
#  parent_comment_id :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :author, foreign_key: :user_id, class_name: :User
  belongs_to :post
  belongs_to :parent_comment, class_name: :Comment

  has_many :children,
    foreign_key: :parent_comment_id,
    class_name: :Comment,
    dependent: :nullify

  validates :content, :user_id, :post_id, presence: true
  validates :content, length: {
    minimum: 25,
    message: "Don't spam. Big brother see you!"
  }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    # @comment.user_id = current_user.id
    @comment.author = current_user

    if @comment.save
      flash[:notice] = 'Comments was added successfully'
      redirect_to post_url(@comment.post_id)
    elsif @comment.parent_comment_id
      flash[:errors] = @comment.errors.full_messages
      redirect_to comment_url(@comment.parent_comment_id)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to new_post_comments_url(@comment.post_id)
    end
  end

  def show
    @comment = Comment.find_by_id(params[:id])
  end

  def upvote
    Vote.create!(value: 1, voteable_id: params[:id], voteable_type: "Comment")
    redirect_to post_url(params[:post_id])
  end

  def downvote
    Vote.create!(value: -1, voteable_id: params[:id], voteable_type: "Comment")
    redirect_to post_url(params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/new.html.erb
<% post = Post.find_by_id(params[:post_id]) %>
<h1>Add new comment to <%= post.title %></h1>

<form action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[post_id]" value="<%= params[:post_id] %>">
  <label>
    <textarea name="comment[content]" rows="8" cols="80">
      <%= @comment.content %>
    </textarea>
  </label>

  <input type="submit" value="Add Comment">
</form>

<%= link_to 'Back', post_url(post) %>

app/views/comments/show.html.erb
<h1>Reply to Comment</h1>

<p><%= @comment.content %>
  <small>by <%= @comment.author.username %></small> |
  <small><%= time_ago_in_words(@comment.created_at) %> ago</small>
</p>

<form action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">
  <label>
    <textarea name="comment[content]" rows="8" cols="80">
    </textarea>
  </label>

  <input type="submit" value="Add Comment">
</form>

<%= link_to "Back to post", post_url(@comment.post_id) %>