config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: :destroy
  resources :posts, except: :index do
    resource :comments, only: :new
    member do
      post 'upvote'
      post 'downvote'
    end
  end
  resources :comments, only: [:create, :show] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end

end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text             not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :description, :user_id, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator, foreign_key: :user_id, class_name: :User
  has_many :post_subs, dependent: :destroy, inverse_of: :sub
  has_many :posts, through: :post_subs

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :set_sub, only: [:edit, :update, :show, :is_moderator?]
  before_action :require_moderator, only: [:edit, :update]

  helper_method :is_moderator?

  def index
    @subs = Sub.all
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id

    if @sub.save
      flash[:notice] = 'Sub created successfully'
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    if @sub.update_attributes(sub_params)
      flash[:notice] = 'Sub updated successfully'
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
  end

  def is_moderator?
    @sub.moderator == current_user
  end

  private

  def require_moderator
    redirect_to sub_url(@sub) unless is_moderator?
  end

  def set_sub
    @sub = Sub.find_by_id(params[:id])
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<% action_url = sub.persisted? ? sub_url(sub) : subs_url %>

<form action="<%= action_url %>" method="post">
  <%= auth_token %>

  <% if sub.persisted? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label for="title">title</label>
  <input id="title"
         type="text"
         name="sub[title]"
         value="<%= sub.title %>">

  <label for="description">Description</label>
  <input id="description"
         type="text"
         name="sub[description]"
         value="<%= sub.description %>">

  <input type="submit" value="Submit">
</form>

app/views/subs/edit.html.erb
<h1>Edit a sub</h1>

<%= render "form", sub: @sub %>

app/views/subs/index.html.erb
<h1>All Subs</h1>

<ul>
  <% @subs.each do |sub| %>
    <li><%= link_to sub.title, sub_url(sub) %></li>
  <% end %>
</ul>

<%= link_to "New sub", new_sub_url %>

app/views/subs/new.html.erb
<h1>Creating New Sub</h1>

<%= render "form", sub: @sub %>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<p><%= @sub.description %></p>

<% if is_moderator? %>
  <%= link_to 'Edit Sub', edit_sub_url(@sub) %>
<% end %>

<br>
<%= link_to "Make a new post", new_post_url(sub_id: @sub.id) %>

<ul>
  <% @sub.posts.includes(:votes).each do |post| %>
    <li>(<%= post.score %>)<%= link_to post.title, post_url(post) %></li>
  <% end %>
</ul>