config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: :destroy
  resources :posts, except: :index do
    resource :comments, only: :new
    member do
      post 'upvote'
      post 'downvote'
    end
  end
  resources :comments, only: [:create, :show] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  include Voteable

  belongs_to :author, foreign_key: :user_id, class_name: :User
  has_many :post_subs, dependent: :destroy, inverse_of: :post
  has_many :subs, through: :post_subs
  has_many :comments

  validates :title, :user_id, presence: true

  def self.posts_with_scores
    Post.joins(:votes).group(:id).sum(:value)
  end

  def comments_by_parent_id
    all_comments = comments.includes(:author)

    comments_hash = Hash.new { |h, k| h[k] = [] }

    all_comments.each do |comment|
      comments_hash[comment.parent_comment_id] << comment
    end

    comments_hash
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :show, :destroy, :is_author?]
  before_action :require_author, only: [:edit, :update, :destroy]

  helper_method :is_author?

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      flash[:notice] = 'Post created successfully'
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      flash[:notice] = 'Post updated successfully'
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @all_comments_hash = @post.comments_by_parent_id
  end

  def destroy
    @post.destroy!
    redirect_to subs_url
  end

  def upvote
    Vote.create!(value: 1, voteable_id: params[:id], voteable_type: "Post")
    render :show
  end

  def downvote
    Vote.create!(value: -1, voteable_id: params[:id], voteable_type: "Post")
    render :show
  end

  def is_author?
    @post.user_id == current_user.id
  end

  private

  def require_author
    redirect_to post_url(@post) unless is_author?
  end

  def set_post
    @post ||= Post.find_by_id(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<li><%= comment.content %> <br>
  <small>by <%= comment.author.username %></small> |
  <small><%= time_ago_in_words(comment.created_at) %> ago</small>
  <br>
  <%= link_to "Reply", comment_url(comment) %>
  <% if all_comments_hash[comment.id] %>
    <ul class="child_comments">
      <% all_comments_hash[comment.id].each do |child_comment| %>
      <%= render "comment", comment: child_comment, all_comments_hash: all_comments_hash %>
      <% end %>
    </ul>
  <% end %>
</li>

app/views/posts/_form.html.erb
<% action_url = post.persisted? ? post_url(post) : posts_url %>

<form action="<%= action_url %>" method="post">
  <%= auth_token %>

  <% if post.persisted? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label for="title">title</label>
  <input id="title"
         type="text"
         name="post[title]"
         value="<%= post.title %>">

  <label for="url">url</label>
  <input id="url"
         type="text"
         name="post[url]"
         value="<%= post.url %>">

  <label for="content">Content</label>
  <input id="content"
         type="text"
         name="post[content]"
         value="<%= post.content %>">

  <br>
  <label for="subs">Subs</label>
  <input type="hidden" name="post[sub_ids][]" value="">

  <% Sub.all.each do |sub| %>
    <br>
    <label>
    <input type="checkbox"
           name="post[sub_ids][]"
           value="<%= sub.id %>"
           <%= "checked" if post.sub_ids.include?(sub.id) %>>
    <%= sub.title %>
    </label>
  <% end %>
  <br>
  <input type="submit" value="Submit">
</form>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form', post: @post %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<h1>Show</h1>

<%= @post.title %>
<%= @post.url %>
<%= @post.content %>

<% if is_author? %>
  <%= link_to 'Edit Post', edit_post_url(@post) %>
<% end %>
<br>
<!-- render comments -->
<ul>
  <% @all_comments_hash[nil].each do |comment| %>
    <%= render "comment", comment: comment, all_comments_hash: @all_comments_hash %>
  <% end %>
</ul>

<br>
<%= link_to 'Make new comment', new_post_comments_url(@post) %>

<br>
<%= link_to 'Back', subs_url %>